[tool.poetry]
name = "exact-hidden-markov-models"
version = "0.1.0"
description = ""
authors = ["egrillot <44230801+egrillot@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "exact_hidden_markov_models"}]

[tool.poetry.dependencies]
<<<<<<< HEAD
python = ">=3.10,<3.11"
tensorflow = "^2.11.0"
numpy = "^1.24.1"
hmmlearn = "^0.2.8"
matplotlib = "^3.6.3"
scipy = "^1.10.0"
sklearn = "^0.0.post1"
simdkalman = "^1.0.2"
keras = "^2.11.0"

=======
python = "^3.10.7"
tensorflow-io-gcs-filesystem = { version = "^2.11.0", python = ">=3.10.7,<3.11" }
>>>>>>> 838d69472f842fbe605665bf97d72d39c6f98933

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
